#!/bin/bash

cd ~/pwdir
dir=~/tensorflow-1.4-billion-password-analysis/BreachCompilation/data/

for i in {a..z}; do mkdir $i && find $dir -type f -exec cat -v {} + | cut -d ";" -f 2 | cut -d ":" -f 2 | grep -i ^$i >> $i/$i.tmp & done
for i in {0..9}; do mkdir $i && find $dir -type f -exec cat -v {} + | cut -d ";" -f 2 | cut -d ":" -f 2 | grep -i ^$i >> $i/$i.tmp & done

jobs

wait
echo "Done!"
for i in {a..z}; do cat -v  $i/$i.tmp | sed '/^$/d' | sort -h | unique $i/$i & done
for i in {0..9}; do cat -v  $i/$i.tmp | sed '/^$/d' | sort -h | unique $i/$i & done

wait
echo "Done!"

for i in {0..9}; do cat $i/$i >> megalist.txt ; done
for i in {a..z}; do cat $i/$i >> megalist.txt ; done
echo "Complete!"
